version: "2"
services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./:/opt/robot

  database:
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none
